# services/auth_service/swagger.yaml
openapi: 3.0.0
info:
  title: Travel Authentication Service
  version: 1.0.0
paths:
  /auth/verify:
    post:
      summary: Verify authentication token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
      responses:
        '200':
          description: Token is valid
        '401':
          description: Invalid or expired token
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT