# services/destination_service/swagger.yaml
openapi: 3.0.0
info:
  title: Travel Destination Service
  version: 1.0.0
paths:
  /destinations:
    get:
      summary: Retrieve all destinations
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of destinations
  /destinations/{id}:
    delete:
      summary: Delete a specific destination
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Destination deleted successfully
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT